addons:
  apt:
    packages:
    - lib32z1
    - lib32stdc++6

language: c

sudo: false

env:
  - VERSION=1.8
  - VERSION=1.9
  - VERSION=1.10

matrix:
  allow_failures:
    - env: VERSION=1.10
    
script:
- 'if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then bash ci/test.sh $VERSION; fi'
- 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash ci/build.sh $TRAVIS_TAG $VERSION; fi'

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: f7VZTzyGTGx+eMR6hTW8oe2uZDU2enRl6RRle5kCylyRwtW7S2SmAXaFgu0ekbrrn4qtKZ5YIDkHT//q3yz9lRNGubDYbqbmvZYBBVf5VlXR5yQJbWOhR2LH4299IzwdBgnV4KhDHEri4GnflMZAGqaVIAOHyw3uiD9c6RqmvQ34Oo6ia1adb18imQf2q8q6WTweRB0VWahz+54RCL/Ruru6tcHQ7Iq89kv+adCIewRmiO5eX3fXYiRkRZQlpHge1AF+heVjJDNKSkDfHTHZ11MCdsoY0OxnKB/9Y3LoCoRbsroYTU6Z0JXZXsSAVYucacKu2sC3p/2A+DPqn54spJZiu/DEveDKMqpwKsi3IAewN83pW81CcIGZTIivsCI7K4aXszqwR5Z8FszOsq0CcrcE7qL9mZmcLJMHjo4ZwZP2gYtqW0LJcbnrA2DNs/r2SHQd9coX6nGPMSkMoei8ABYoh7NwQak2YPuugtfdfsq4J8t7GAHlVi5XuEDg5rHJiCDKULBc0mbYrmVPUo+7PfM+oiFqK27LPpkYgaidPkXHYZweqjtMpvBqFWaC8DBOeYSfkwb4vexS4TLWHyVjOEDuIy+IXjeIhuyin08K6JMF2qsNyvzefm8VbKsjntA50dwaoFry6ji5IX6vNTPKMe0OyVMs0ST6l5Xi4EDtYQ0=
  file: HexSpy.zip
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: Hexer10/HexSpy
    condition: $VERSION = 1.9